version: '3'
services:
  app:
    build:
      context: .
      target: ${TARGET:-dev}
    working_dir: /app
    volumes:
      - ${PWD:-./}:/${TARGET:-app}
    ports:
      - "8083:8083"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "testcase"
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    command: sh -c 'echo "[client]\nuser=root\npassword=$${DB_PASSWORD}" > /root/.my.cnf && docker-entrypoint.sh mysqld'
    volumes:
      - "dbdata:/var/lib/mysql"
  
volumes:
  dbdata: